
const GET_TODOS = 'GET_TODOS';
const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const COMPLETE_TODO = 'COMPLETE_TODO';

export {
    GET_TODOS,
    ADD_TODO,
    DELETE_TODO,
    COMPLETE_TODO,
}